# -*- coding: utf-8 -*-
"""data_science.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nr5Io2RbPSbeWgUCadtI7LUgn5vMR5uc
"""

# This installs R support
!apt-get install -y libssl-dev libcurl4-openssl-dev libxml2-dev
!Rscript -e "IRkernel::installspec(user = FALSE)"

# Install R magic
!pip install -q rpy2

# Commented out IPython magic to ensure Python compatibility.
# %load_ext rpy2.ipython

"""1. Handle Outliers in R"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# data(iris)
# 
# Q1 <- quantile(iris$Sepal.Length, 0.25)
# Q3 <- quantile(iris$Sepal.Length, 0.75)
# IQR_value <- Q3 - Q1
# 
# lower_bound <- Q1 - 1.5 * IQR_value
# upper_bound <- Q3 + 1.5 * IQR_value
# 
# iris_no_outliers <- iris[iris$Sepal.Length >= lower_bound & iris$Sepal.Length <= upper_bound, ]
# 
# cat("Outliers removed based on Sepal.Length:", nrow(iris) - nrow(iris_no_outliers), "\n")
# 
#

!pip install -q rpy2

# Commented out IPython magic to ensure Python compatibility.
# %load_ext rpy2.ipython

"""2. Handle Invalid Values in R"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# # Simulate invalid values
# iris_with_invalid <- iris
# iris_with_invalid$Sepal.Length[c(5, 10)] <- NA  # Add missing (invalid) values
# 
# # Handle: Replace NA with median
# iris_with_invalid$Sepal.Length[is.na(iris_with_invalid$Sepal.Length)] <- median(iris$Sepal.Length, na.rm = TRUE)
# 
# # View result
# print("Handled invalid values (NA replaced with median):")
# summary(iris_with_invalid$Sepal.Length)
#

"""3. Visualize Iris Dataset Using Mosaic Plot"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# install.packages(c("zoo", "colorspace", "lmtest", "vcd"))
#

# Commented out IPython magic to ensure Python compatibility.
# %%R
# library(vcd)

# Commented out IPython magic to ensure Python compatibility.
# %%R
# mosaic(
#   ~ Species + cut(Petal.Width, breaks=3),
#   data=iris,
#   shade=TRUE,
#   legend=TRUE,
#   main="Mosaic Plot: Species vs Petal Width"
# )
#

!pip install -q rpy2

# Commented out IPython magic to ensure Python compatibility.
# %load_ext rpy2.ipython

"""5. Linear Regression on Mouse Data"""

# Commented out IPython magic to ensure Python compatibility.
# %%R
# # Mice data
# height <- c(140,142,150,147,139,152,154,135,148,147)
# weight <- c(59, 61, 66, 62, 57, 68, 69, 58, 63, 62)
# 
# # Linear regression
# model <- lm(weight ~ height)
# 
# # Summary
# print(summary(model))
# 
# # Plot regression line
# plot(height, weight,
#      main = "Linear Regression: Height vs Weight",
#      xlab = "Height", ylab = "Weight", pch = 16)
# abline(model, col = "red", lwd = 2)
#

